const typing = new Typed('#typp-bdj' ,{
    strings: ['<strong class="typing-class">You have many possibilities</strong>',
    '<strong class="typing-class">We do it for you</strong>',
    '<strong class="typing-class">Avoid working too much</strong>',
    '<strong class="typing-class">Fast and effective procedures</strong>',
    '<strong class="typing-class">¡¡ Choose us !!</strong>',
    '<strong class="typing-class">AVOID WORK^1100 is the answer </strong>',
    '<strong class="typing-class">This Proyect WAS Making to Student of POLITECNICO DE LA COSTA</strong>',
    ],
    typeSpeed: 40,
    loop:true,
    fadeOutDelay: 500,
    backSpeed: 23,
    backDelay: 2000,
    smartBackspace: true,
});